ALTER TABLE backtest_runs ADD COLUMN IF NOT EXISTS win_rate NUMERIC;
ALTER TABLE backtest_runs ADD COLUMN IF NOT EXISTS profit_factor NUMERIC;
ALTER TABLE backtest_runs ADD COLUMN IF NOT EXISTS expectancy NUMERIC;
ALTER TABLE backtest_runs ADD COLUMN IF NOT EXISTS avg_win NUMERIC;
ALTER TABLE backtest_runs ADD COLUMN IF NOT EXISTS avg_loss NUMERIC;