CREATE TABLE IF NOT EXISTS live_campaign_legs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  campaign_id UUID NOT NULL REFERENCES live_campaigns(id) ON DELETE CASCADE,
  strategy_id UUID REFERENCES strategy_configs(id) ON DELETE SET NULL,
  strategy_version INTEGER NOT NULL DEFAULT 1,
  cycle_id UUID NOT NULL,
  leg_id TEXT NOT NULL,
  role TEXT NOT NULL,
  side TEXT NOT NULL,
  option_type TEXT NOT NULL,
  execution_rank INTEGER NOT NULL,
  expiry TEXT NOT NULL,
  strike NUMERIC NOT NULL,
  instrument_key TEXT NOT NULL,
  trading_symbol TEXT,
  lot_size INTEGER NOT NULL,
  lots INTEGER NOT NULL,
  requested_quantity INTEGER NOT NULL,
  filled_quantity INTEGER NOT NULL DEFAULT 0,
  entry_price NUMERIC,
  exit_price NUMERIC,
  current_price NUMERIC,
  pnl NUMERIC NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'PENDING',
  entry_order_id UUID,
  exit_order_id UUID,
  entry_at TIMESTAMPTZ,
  exit_at TIMESTAMPTZ,
  last_mark_at TIMESTAMPTZ,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb
)