CREATE TABLE IF NOT EXISTS trading_journal_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id text NOT NULL DEFAULT current_setting('hatchable.user_id', true),
  source_mode text NOT NULL,
  source_leg_id text NOT NULL,
  campaign_id uuid NOT NULL,
  strategy_id uuid NULL,
  strategy_version integer NOT NULL DEFAULT 1,
  strategy_name text NULL,
  underlying text NOT NULL,
  cycle_id uuid NULL,
  leg_id text NULL,
  role text NULL,
  side text NULL,
  option_type text NULL,
  expiry text NULL,
  strike numeric NULL,
  instrument_key text NULL,
  trading_symbol text NULL,
  lot_size integer NULL,
  lots integer NULL,
  requested_quantity integer NULL,
  filled_quantity integer NOT NULL DEFAULT 0,
  entry_price numeric NULL,
  exit_price numeric NULL,
  current_price numeric NULL,
  pnl numeric NOT NULL DEFAULT 0,
  status text NOT NULL,
  entry_at timestamptz NULL,
  exit_at timestamptz NULL,
  total_rolls integer NOT NULL DEFAULT 0,
  strategy_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  execution_details jsonb NOT NULL DEFAULT '{}'::jsonb,
  journal_date date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id, source_mode, source_leg_id)
)