import { db } from 'hatchable';

export const access = 'user';
export const methods = ['GET','POST'];

const UNDERLYINGS={'NIFTY 50':'NSE_INDEX|Nifty 50','BANK NIFTY':'NSE_INDEX|Nifty Bank','SENSEX':'BSE_INDEX|SENSEX','BANKEX':'BSE_INDEX|BANKEX'};
const TF={'3m':3,'5m':5,'15m':15,'30m':30,'1h':60};
const rank=(s,t)=>({ 'BUY:CE':1,'BUY:PE':2,'SELL:CE':3,'SELL:PE':4 }[`${s}:${t}`]||99);
const n=(v,d=NaN)=>Number.isFinite(Number(v))?Number(v):d;
const date=(d)=>new Date(d+'T00:00:00Z');
const iso=(d)=>d.toISOString().slice(0,10);
const addDays=(d,x)=>{const z=new Date(d.getTime());z.setUTCDate(z.getUTCDate()+x);return z};
const minutes=(x)=>{const [h,m]=String(x||'09:45').split(':').map(Number);return h*60+m};
const ist=new Date(Date.now()+330*60000);
const istMinutes=(ts)=>{const d=new Date(new Date(ts).getTime()+330*60000);return d.getUTCHours()*60+d.getUTCMinutes()};
const interval=(tf)=>tf==='1h'?['hours','1']:['minutes',String(TF[tf])];
const parse=(rows)=>rows.map(x=>({timestamp:x[0],open:n(x[1]),high:n(x[2]),low:n(x[3]),close:n(x[4]),volume:n(x[5],0),oi:n(x[6],0)})).filter(x=>[x.open,x.high,x.low,x.close].every(Number.isFinite));
function completed(c,tf){return new Date(c.timestamp).getTime()+TF[tf]*60000<=Date.now();}
function indicators(c,ap,tp){if(c.length<Math.max(ap*2+1,tp+1))return null;const tr=[],p=[],m=[];for(let i=1;i<c.length;i++){const a=c[i-1],b=c[i],up=b.high-a.high,down=a.low-b.low;tr.push(Math.max(b.high-b.low,Math.abs(b.high-a.close),Math.abs(b.low-a.close)));p.push(up>down&&up>0?up:0);m.push(down>up&&down>0?down:0)}let atr=null,pp=null,mm=null;const dx=[];let pd=0,md=0;for(let i=0;i<tr.length;i++){if(i===tp-1)atr=tr.slice(0,tp).reduce((a,b)=>a+b,0)/tp;else if(i>=tp)atr=((atr*(tp-1))+tr[i])/tp;if(i===ap-1){pp=p.slice(0,ap).reduce((a,b)=>a+b,0)/ap;mm=m.slice(0,ap).reduce((a,b)=>a+b,0)/ap}else if(i>=ap){pp=((pp*(ap-1))+p[i])/ap;mm=((mm*(ap-1))+m[i])/ap}if(atr&&pp!==null&&mm!==null){const plus=100*pp/atr,minus=100*mm/atr,den=plus+minus;dx.push(den?100*Math.abs(plus-minus)/den:0)}}if(dx.length<ap||atr===null)return null;let adx=dx.slice(0,ap).reduce((a,b)=>a+b,0)/ap;for(let i=ap;i<dx.length;i++)adx=((adx*(ap-1))+dx[i])/ap;const plus=100*pp/atr,minus=100*mm/atr;return {adx,plus_di:plus,minus_di:minus,atr};}
function regime(i,r,t){r=r||{};const a=i.adx<n(r.adx_less_than,t),p=r.adx_below_plus_di===false||i.adx<i.plus_di,m=r.adx_below_minus_di===false||i.adx<i.minus_di;return a&&p&&m;}
async function broker(uid){const q=await db.query('SELECT access_token,status,expires_at FROM broker_connections WHERE user_id=$1 LIMIT 1',[uid]);const c=q.rows[0];if(!c||c.status!=='CONNECTED'||!c.access_token)throw Error('UPSTOX_NOT_CONNECTED');if(c.expires_at&&new Date(c.expires_at)<=new Date())throw Error('UPSTOX_TOKEN_EXPIRED');return c.access_token;}
async function getCandles(token,key,tf,from,to){const [u,i]=interval(tf),h={Accept:'application/json',Authorization:'Bearer '+token};const url='https://api.upstox.com/v3/historical-candle/'+encodeURIComponent(key)+'/'+u+'/'+i+'/'+encodeURIComponent(to)+'/'+encodeURIComponent(from);const r=await fetch(url,{headers:h});const d=await r.json().catch(()=>({}));if(!r.ok||d.status!=='success')throw Error('HISTORICAL_CANDLE_FAILED');return parse(d.data?.candles||[]);}
async function contracts(token,key,expiry){const h={Accept:'application/json',Authorization:'Bearer '+token};const r=await fetch('https://api.upstox.com/v2/option/contract?instrument_key='+encodeURIComponent(key)+'&expiry_date='+encodeURIComponent(expiry),{headers:h});const d=await r.json().catch(()=>({}));if(!r.ok||d.status!=='success'||!Array.isArray(d.data)||!d.data.length)throw Error('HISTORICAL_OPTION_CONTRACTS_UNAVAILABLE');return d.data;}
function choose(cs,leg,spot){const type=leg.option_type==='PE'?'PE':'CE',method=leg.selection_method||'ATM';if(['PREMIUM','DELTA'].includes(method))return {error:'HISTORICAL_SELECTION_METHOD_UNSUPPORTED',method};let pool=cs.filter(c=>c.option_type===type&&n(c.strike_price)!=null&&c.instrument_key);if(method==='CUSTOM_STRIKE'){pool=pool.filter(c=>n(c.strike_price)===n(leg.custom_strike));}else{const off=Math.max(0,parseInt(leg.strike_offset,10)||0);const strikes=[...new Set(pool.map(c=>n(c.strike_price)))].sort((a,b)=>a-b);if(!strikes.length)return {error:'NO_HISTORICAL_CONTRACT'};let ai=strikes.reduce((best,x,i)=>Math.abs(x-spot)<Math.abs(strikes[best]-spot)?i:best,0);if(method==='STRIKE_OFFSET'){const dir=(leg.distance_mode==='ITM'?(type==='CE'?-1:1):(type==='CE'?1:-1));ai+=dir*off;}if(ai<0||ai>=strikes.length)return {error:'STRIKE_OFFSET_OUT_OF_RANGE'};const target=strikes[ai];pool=pool.filter(c=>n(c.strike_price)===target);}const c=pool[0];if(!c)return {error:'NO_HISTORICAL_CONTRACT'};return {contract:c,option_type:type};}
function fill(px,side,slip){const s=Math.max(0,n(slip,0))/10000;return side==='BUY'?px*(1+s):px*(1-s);}

export default async function(req,res){
 const uid=req.user.id;
 if(req.method==='GET'){const q=await db.query('SELECT * FROM backtest_runs WHERE user_id=$1 ORDER BY created_at DESC LIMIT 25',[uid]);return res.json({runs:q.rows});}
 const b=req.body||{}, strategyId=String(b.strategy_id||'');if(!strategyId)return res.status(400).json({error:'strategy_id required'});
 const s=(await db.query('SELECT * FROM strategy_configs WHERE id=$1 AND user_id=$2 LIMIT 1',[strategyId,uid])).rows[0];if(!s)return res.status(404).json({error:'STRATEGY_NOT_FOUND'});
 const v=Number(s.version||1),vq=(await db.query('SELECT version_number,config FROM strategy_versions WHERE strategy_id=$1 AND user_id=$2 AND version_number=$3 LIMIT 1',[strategyId,uid,v])).rows[0];if(!vq)return res.status(409).json({error:'STRATEGY_VERSION_NOT_FOUND'});
 const cfg={...s,...(vq.config||{}),leg_config:(vq.config?.legs||s.leg_config||[])};const tf=cfg.timeframe||'15m',under=cfg.underlying||'NIFTY 50';if(!TF[tf]||!UNDERLYINGS[under])return res.status(400).json({error:'INVALID_MARKET_CONFIGURATION'});
 const startDate=String(b.start_date||''),endDate=String(b.end_date||''),expiry=String(b.expiry_date||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(startDate)||!/^\d{4}-\d{2}-\d{2}$/.test(endDate)||!/^\d{4}-\d{2}-\d{2}$/.test(expiry)||startDate>endDate)return res.status(400).json({error:'INVALID_DATE_RANGE'});
 const days=Math.round((date(endDate)-date(startDate))/86400000)+1;if(days>62)return res.status(400).json({error:'DATE_RANGE_MAX_62_DAYS'});
 const unsupported=(cfg.leg_config||[]).filter(x=>x.enabled!==false&&['PREMIUM','DELTA'].includes(x.selection_method||'ATM'));if(unsupported.length)return res.status(400).json({error:'HISTORICAL_SELECTION_METHOD_UNSUPPORTED',methods:[...new Set(unsupported.map(x=>x.selection_method))],note:'Historical option-chain snapshots for premium/delta selection are not fabricated.'});
 const token=await broker(uid), key=UNDERLYINGS[under], from=iso(addDays(date(startDate),-Math.max(30,Number(cfg.adx_period||14)*3))), to=endDate;
 const run=(await db.query('INSERT INTO backtest_runs (user_id,strategy_id,strategy_version,underlying,timeframe,candle_type,start_date,end_date,expiry_date,status,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *',[uid,strategyId,v,under,tf,cfg.candle_type||'OHLC',startDate,endDate,expiry,'RUNNING','Historical option prices use Upstox candle closes with configurable slippage; no synthetic option pricing.'])) .rows[0];
 try{
  const uc=await getCandles(token,key,tf,from,to);const cc=uc.filter(x=>completed(x,tf));if(!cc.length)throw Error('NO_HISTORICAL_CANDLES');
  const cs=await contracts(token,key,expiry), cache=new Map();const legs=[];let active=null,realized=0,grossRealized=0,fees=0,slippage=0,totalStructures=0,rolls=0,wins=0,losses=0;
  async function price(inst,ts){if(!cache.has(inst))cache.set(inst,await getCandles(token,inst,tf,startDate,endDate));const arr=cache.get(inst);let best=null;for(const x of arr){if(new Date(x.timestamp)<=new Date(ts))best=x;else break;}return best?.close;}
  async function closeStruct(at,reason,spot){if(!active)return;let pnl=0;for(const l of active){const p=await price(l.instrument_key,at);if(!Number.isFinite(p))throw Error('HISTORICAL_OPTION_PRICE_MISSING');const ep=fill(p,l.side==='BUY'?'SELL':'BUY',b.slippage_bps);const gp=(l.side==='BUY'?1:-1)*(ep-l.entry_price)*l.quantity;const fee=Math.max(0,n(b.fee_per_leg,0));const sl=Math.abs(ep-l.entry_price)*l.quantity-Math.abs(p-l.entry_price)*l.quantity;fees+=fee;slippage+=Math.max(0,sl);pnl+=gp-fee;await db.query('INSERT INTO backtest_trades (run_id,user_id,structure_id,entry_at,exit_at,action,exit_reason,underlying_spot,option_type,side,role,strike,instrument_key,trading_symbol,quantity,entry_price,exit_price,gross_pnl,fees,slippage,net_pnl,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22)',[run.id,uid,active.id,active.entry_at,at,'EXIT',reason,spot,l.option_type,l.side,l.role,l.strike,l.instrument_key,l.trading_symbol,l.quantity,l.entry_price,ep,gp,fee,Math.max(0,sl),gp-fee,JSON.stringify({rank:l.execution_rank})]);}realized+=pnl;active=null;}
  async function openStruct(at,spot,sellOnly=false){const enabled=(cfg.leg_config||[]).filter(x=>x.enabled!==false&&(!sellOnly||String(x.side||'SELL').toUpperCase()==='SELL'));const resolved=[];for(const leg of enabled){const r=choose(cs,leg,spot);if(r.error)throw Error(r.error);const p=await price(r.contract.instrument_key,at);if(!Number.isFinite(p))throw Error('HISTORICAL_OPTION_PRICE_MISSING');resolved.push({...r.contract,option_type:r.option_type,side:leg.side==='BUY'?'BUY':'SELL',role:leg.role==='HEDGE'?'HEDGE':'PRIMARY',execution_rank:rank(leg.side==='BUY'?'BUY':'SELL',r.option_type),quantity:Math.max(1,(parseInt(leg.quantity,10)||1))*(Number(r.contract.lot_size)||1),entry_price:fill(p,leg.side==='BUY'?'BUY':'SELL',b.slippage_bps),entry_at:at,leg_id:String(leg.id)});}resolved.sort((a,b)=>a.execution_rank-b.execution_rank);const retained=sellOnly&&active?[...active.legs]:[];active={id:'S'+(totalStructures+1),entry_at:at,legs:[...retained,...resolved]};totalStructures++;for(const l of resolved){await db.query('INSERT INTO backtest_trades (run_id,user_id,structure_id,entry_at,action,underlying_spot,option_type,side,role,strike,instrument_key,trading_symbol,quantity,entry_price,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)',[run.id,uid,active.id,at,'ENTRY',spot,l.option_type,l.side,l.role,l.strike,l.instrument_key,l.trading_symbol,l.quantity,l.entry_price,JSON.stringify({rank:l.execution_rank,fill_basis:'historical_option_candle_close',sell_only_roll:sellOnly})]);}}
  const start=minutes(cfg.start_time||'09:45'),sq=minutes(cfg.square_off||'15:15'),confirm=Math.max(1,Number(cfg.confirmation_candles||1)),multi=(cfg.leg_config||[]).filter(x=>x.enabled!==false).length;
  for(let i=0;i<cc.length;i++){const c=cc[i],cm=istMinutes(c.timestamp);if(cm<start)continue;if(cm>=sq){if(active)await closeStruct(c.timestamp,'SQUARE_OFF',c.close);continue;}const ind=indicators(cc.slice(0,i+1),Number(cfg.adx_period||14),Number(cfg.atr_period||14));if(!ind)continue;const upper=c.close+Number(cfg.atr_multiplier||2)*ind.atr,lower=c.close-Number(cfg.atr_multiplier||2)*ind.atr;if(active){if(c.close>active.upper||c.close<active.lower){const sells=active.legs.filter(x=>x.side==='SELL');for(const l of active.legs){const p=await price(l.instrument_key,c.timestamp);if(!Number.isFinite(p))throw Error('HISTORICAL_OPTION_PRICE_MISSING');const exitSide=l.side==='BUY'?'SELL':'BUY';const ep=fill(p,exitSide,b.slippage_bps);const gp=(l.side==='BUY'?1:-1)*(ep-l.entry_price)*l.quantity;const fee=Math.max(0,n(b.fee_per_leg,0));realized+=gp-fee;grossRealized+=gp;fees+=fee;await db.query('INSERT INTO backtest_trades (run_id,user_id,structure_id,entry_at,exit_at,action,exit_reason,underlying_spot,option_type,side,role,strike,instrument_key,trading_symbol,quantity,entry_price,exit_price,gross_pnl,fees,slippage,net_pnl,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22)',[run.id,uid,active.id,active.entry_at,c.timestamp,'EXIT','CORRIDOR_BREACH_ROLL',c.close,l.option_type,l.side,l.role,l.strike,l.instrument_key,l.trading_symbol,l.quantity,l.entry_price,ep,gp,fee,0,gp-fee,JSON.stringify({rank:l.execution_rank,complete_structure_roll:true})]);}rolls++;active=null;await openStruct(c.timestamp,c.close,false);if(active){active.upper=c.close+Number(cfg.atr_multiplier||2)*ind.atr;active.lower=c.close-Number(cfg.atr_multiplier||2)*ind.atr;}continue;}continue;}const recent=cc.slice(Math.max(0,i-confirm+1),i+1);const pass=recent.length===confirm&&recent.every(x=>{const ix=indicators(cc.slice(0,cc.indexOf(x)+1),Number(cfg.adx_period||14),Number(cfg.atr_period||14));return ix&&regime(ix,cfg.regime_rule,cfg.adx_threshold)});if(pass&&!active){await openStruct(c.timestamp,c.close);active.upper=upper;active.lower=lower;}}
  if(active){await closeStruct(endDate+'T15:15:00+05:30','END_OF_TEST',cc[cc.length-1].close);}
  const tq=await db.query('SELECT net_pnl,gross_pnl FROM backtest_trades WHERE run_id=$1 AND user_id=$2 AND action=\'EXIT\'',[run.id,uid]);const nets=tq.rows.map(x=>Number(x.net_pnl||0));grossRealized=tq.rows.reduce((a,x)=>a+Number(x.gross_pnl||0),0);const total=nets.reduce((a,x)=>a+x,0);wins=nets.filter(x=>x>0).length;losses=nets.filter(x=>x<0).length;const grossWins=nets.filter(x=>x>0).reduce((a,x)=>a+x,0),grossLosses=Math.abs(nets.filter(x=>x<0).reduce((a,x)=>a+x,0));const profitFactor=grossLosses?grossWins/grossLosses:(grossWins?Infinity:null),winRate=nets.length?wins/nets.length:null,avgWin=wins?grossWins/wins:null,avgLoss=losses?grossLosses/losses:null,expectancy=nets.length?total/nets.length:null;
  const eqRows=await db.query('SELECT exit_at, SUM(net_pnl) OVER (ORDER BY exit_at,id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS equity FROM backtest_trades WHERE run_id=$1 AND user_id=$2 AND action=\'EXIT\' ORDER BY exit_at,id',[run.id,uid]);let peak=0,maxDrawdown=0;for(const r of eqRows.rows){const e=Number(r.equity||0);peak=Math.max(peak,e);maxDrawdown=Math.min(maxDrawdown,e-peak);}
  await db.query('UPDATE backtest_runs SET status=$1,realized_pnl=$2,total_pnl=$2,gross_pnl=$3,total_trades=$4,winning_trades=$5,losing_trades=$6,fees=$7,slippage=$8,max_drawdown=$9,total_structures=$10,rolls=$11,data_quality=$12,engine_version=$13,win_rate=$14,profit_factor=$15,expectancy=$16,avg_win=$17,avg_loss=$18,completed_at=now() WHERE id=$19 AND user_id=$20',['COMPLETED',total,grossRealized,nets.length,wins,losses,fees,slippage,maxDrawdown,totalStructures,rolls,'VERIFIED_SOURCE_DATA','v2',winRate,Number.isFinite(profitFactor)?profitFactor:null,expectancy,avgWin,avgLoss,run.id,uid]);
  return res.json({run:{...run,status:'COMPLETED',total_pnl:total,gross_pnl:grossRealized,total_trades:nets.length,winning_trades:wins,losing_trades:losses,fees,slippage,max_drawdown:maxDrawdown,total_structures:totalStructures,rolls,data_quality:'VERIFIED_SOURCE_DATA',engine_version:'v2',win_rate:nets.length?wins/nets.length:null,profit_factor:Number.isFinite(profitFactor)?profitFactor:null},disclosure:'Historical option fills use Upstox historical option candles at candle close plus configured slippage. Premium/delta historical selection is blocked because historical chain snapshots are not fabricated.',trades:(await db.query('SELECT * FROM backtest_trades WHERE run_id=$1 AND user_id=$2 ORDER BY entry_at',[run.id,uid])).rows});
 }catch(e){await db.query('UPDATE backtest_runs SET status=$1,notes=$2,completed_at=now() WHERE id=$3 AND user_id=$4',['FAILED',String(e.message||e),run.id,uid]);return res.status(409).json({error:String(e.message||e),run_id:run.id});}
}